/** 코드 리뷰 프롬프트 빌더 */
export function buildReviewPrompt(baseBranch: string): string {
  return [
    `'${baseBranch}'와 HEAD 사이의 코드 변경사항을 분석하여 한국어로 코드 리뷰해줘.`,
    "",
    "## False Positive 방지 규칙",
    "",
    "- 이 커밋에서 새로 도입된 이슈만 지적할 것. 기존 코드의 문제는 제외",
    "- 코드베이스 나머지와 불일치한 수준의 엄격함 요구 금지",
    "- 추측 금지 — 영향받는 코드 경로를 증명할 수 있어야 함",
    "- 명백히 의도적인 변경은 플래그하지 말 것",
    '- "원저자가 이 점을 알면 스스로 고쳤을까?" 기준으로 판단',
    "- 사소한 스타일/포맷은 린터가 잡지 못하는 것만 지적",
    "- 주관적 의견 제외",
    "",
    "## 톤 가이드라인",
    "",
    "- 사실적(matter-of-fact) 톤. 비난적이거나 과도하게 긍정적이지 않게",
    '- "Great job", "좋습니다" 등 칭찬/사교적 표현 금지',
    "- description은 최대 1문단, 즉시 파악 가능하게",
    "- 이슈 발생 시나리오/환경을 명시적으로 설명",
    "",
    "## 출력 형식",
    "",
    "반드시 아래 JSON 객체 형식으로만 응답해줘. 다른 텍스트 없이 JSON만 출력해줘:",
    "```json",
    "{",
    '  "summary": "변경사항 요약 (마크다운 허용). 1) 변경 개요 2) 주요 변경사항 3) 영향 범위를 포함해줘.",',
    '  "verdict": "approve | request-changes | comment",',
    '  "confidence": 85,',
    '  "findings": [',
    "    {",
    '      "path": "src/example/file.ts",',
    '      "line": 42,',
    '      "endLine": 45,',
    '      "severity": "blocking",',
    '      "title": "Null check 누락으로 런타임 크래시 가능",',
    '      "confidence": 90,',
    '      "description": "문제가 무엇인지 명확히 설명",',
    '      "problemCode": "문제가 되는 코드 인용 (선택)",',
    '      "suggestedFix": "개선된 코드 예시 (선택)",',
    '      "reason": "왜 이 변경이 필요한지 근거"',
    "    }",
    "  ]",
    "}",
    "```",
    "",
    "## 가이드라인",
    "",
    "### summary",
    "- 변경 개요: 어떤 기능/모듈이 변경되었는지",
    "- 주요 변경사항 목록 (bullet point)",
    "- 영향 범위: 이 변경이 영향을 미치는 부분",
    "- 간결하고 명확하게, 비개발자도 이해할 수 있도록 작성",
    "",
    "### verdict",
    '- "approve": blocking 이슈가 없고, 코드 품질이 양호한 경우',
    '- "request-changes": blocking 이슈가 1개 이상인 경우',
    '- "comment": blocking은 없지만 개선 권장사항이 있는 경우',
    "",
    "### confidence",
    "- 리뷰 판단의 확신도 (0-100)",
    "",
    "### findings",
    "- 각 이슈의 severity는 반드시 다음 4단계 중 하나:",
    '  - "blocking": 반드시 수정 필요 (보안 취약점, 버그, 아키텍처 위반)',
    '  - "recommended": 권장 개선 사항 (성능, 가독성, 베스트 프랙티스)',
    '  - "suggestion": 선택적 개선 아이디어 (리팩토링, 최적화 기회)',
    '  - "tech-debt": 향후 개선이 필요한 기술 부채',
    "- title은 80자 이내 명령형 제목 (예: 'Null check 추가 필요')",
    "- confidence는 해당 finding의 확신도 (0-100)",
    "- endLine은 이슈가 여러 줄에 걸칠 때 끝 라인 번호",
    "- 문제가 없으면 빈 배열 []",
  ].join("\n");
}
